# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zr5eOW5001fXVJh3G8OVzH-imwvHgb8b
"""

import json
import os
import time
from pathlib import Path

import numpy as np
import pydicom
import SimpleITK as sitk
import tensorflow as tf
from scipy.ndimage import zoom


# Кастомная MSE функция для совместимости с обученной моделью
def custom_mse(y_true, y_pred):
    return tf.reduce_mean(tf.square(y_true - y_pred))


class CTInferenceProcessor:
    """
    Класс для обработки КТ-исследований и выполнения инференса.
    Принимает готовую папку с DICOM файлами, возвращает dict с результатами.
    """

    def __init__(self, target_size=(128, 128, 64)):
        self.target_size = target_size
        self.model = None
        self.optimal_threshold = 0.01

    def load_model(
        self,
        model_path="pathology_autoencoder.keras",
        threshold_path="pathology_threshold.json",
    ):
        """Загружает модель и порог."""
        try:
            if os.path.exists(model_path):
                self.model = tf.keras.models.load_model(
                    model_path, custom_objects={"custom_mse": custom_mse}
                )
                print(f"✓ Модель загружена из {model_path}")
            else:
                print(f"⚠ Файл модели {model_path} не найден")
                return False

            if os.path.exists(threshold_path):
                with open(threshold_path, "r") as f:
                    threshold_data = json.load(f)
                self.optimal_threshold = threshold_data["optimal_threshold"]
                print(f"✓ Порог загружен: {self.optimal_threshold:.6f}")
            else:
                print("⚠ Файл порога не найден. Использую значение по умолчанию.")

            return True

        except Exception as e:
            print(f"❌ Ошибка загрузки модели/порога: {e}")
            return False

    def is_dicom_file(self, file_path):
        """Проверяет, является ли файл DICOM файлом."""
        try:
            pydicom.dcmread(file_path, stop_before_pixels=True)
            return True
        except:
            return False

    def load_dicom_series(self, directory_path):
        """Загружает серию DICOM файлов из папки."""
        try:
            # Получаем все файлы в папке
            all_files = list(Path(directory_path).iterdir())
            files = [f for f in all_files if f.is_file() and not f.name.startswith(".")]

            if not files:
                print(f"❌ Нет файлов в {directory_path}")
                return None

            print(f"📁 Найдено {len(files)} файлов в {directory_path}")

            # Определяем DICOM файлы
            dicom_files = []
            for file_path in files:
                if self.is_dicom_file(str(file_path)):
                    dicom_files.append(str(file_path))

            if not dicom_files:
                print(
                    "⚠ Не найдено DICOM файлов по сигнатуре, пробуем загрузить все файлы..."
                )
                dicom_files = [str(f) for f in files]

            print(f"🔍 Загружаем {len(dicom_files)} файлов как DICOM")

            # Сортируем файлы для правильной последовательности
            dicom_files.sort()

            reader = sitk.ImageSeriesReader()
            reader.SetFileNames(dicom_files)
            image = reader.Execute()
            print(f"✓ Успешно загружено изображение размером {image.GetSize()}")
            return image

        except Exception as e:
            print(f"❌ Ошибка загрузки DICOM из {directory_path}: {e}")
            return None

    def preprocess_image(self, sitk_image):
        """
        Препроцессинг КТ-изображения (аналогично тренировочному скрипту).
        """
        try:
            # Конвертация в numpy array и обрезка значений HU
            image_array = sitk.GetArrayFromImage(sitk_image)
            image_array = image_array.astype(np.float32)

            print(f"📊 Исходный размер: {image_array.shape}")

            # Ограничение диапазона HU для фокуса на релевантных тканях
            image_array = np.clip(image_array, -1000, 400)

            # Нормализация к диапазону [0, 1]
            image_array = (image_array - (-1000)) / (400 - (-1000))

            # Ресемплинг к целевому размеру
            zoom_factors = [
                self.target_size[0] / image_array.shape[0],
                self.target_size[1] / image_array.shape[1],
                self.target_size[2] / image_array.shape[2],
            ]
            image_array_resized = zoom(image_array, zoom_factors, order=1)

            print(f"📏 Размер после ресемплинга: {image_array_resized.shape}")

            # Добавление размерности канала
            image_array_resized = np.expand_dims(image_array_resized, axis=-1)
            return image_array_resized

        except Exception as e:
            print(f"❌ Ошибка препроцессинга: {e}")
            return None

    def calculate_reconstruction_error(self, volume):
        """Вычисление ошибки реконструкции."""
        try:
            input_array = np.expand_dims(volume, axis=0)
            reconstruction = self.model.predict(input_array, verbose=0)
            mse = np.mean(np.square(volume - reconstruction[0]))
            return mse
        except Exception as e:
            print(f"❌ Ошибка предсказания: {e}")
            return None

    def sigmoid_transform(self, error):
        """Преобразование ошибки в вероятность."""
        scaled_error = (error - self.optimal_threshold) / max(
            self.optimal_threshold, 0.001
        )
        probability = 1 / (1 + np.exp(-scaled_error * 3))
        return probability

    def process_study_folder(self, study_folder_path, study_id="unknown"):
        """
        Основной метод для обработки одной папки с исследованием.
        Возвращает dict с результатами.
        """
        start_time = time.time()

        result = {
            "study_folder_path": str(study_folder_path),
            "study_id": study_id,
            "probability_of_pathology": 0.0,
            "pathology_class": 0,
            "processing_status": "Success",
            "processing_time_seconds": 0.0,
            "error_message": "",
            "reconstruction_error": 0.0,
            "original_image_size": "",
            "processed_image_size": "",
        }

        try:
            print(f"\n🔬 Обработка исследования: {study_folder_path}")

            # Загрузка DICOM серии
            sitk_image = self.load_dicom_series(study_folder_path)
            if sitk_image is None:
                raise Exception("Не удалось загрузить DICOM серию")

            # Сохраняем информацию о исходном размере
            original_size = sitk_image.GetSize()
            result["original_image_size"] = (
                f"{original_size[0]}x{original_size[1]}x{original_size[2]}"
            )

            # Препроцессинг
            processed_volume = self.preprocess_image(sitk_image)
            if processed_volume is None:
                raise Exception("Ошибка препроцессинга изображения")

            # Сохраняем информацию о обработанном размере
            result["processed_image_size"] = (
                f"{processed_volume.shape[0]}x{processed_volume.shape[1]}x{processed_volume.shape[2]}"
            )

            # Вычисление ошибки реконструкции
            reconstruction_error = self.calculate_reconstruction_error(processed_volume)
            if reconstruction_error is None:
                raise Exception("Ошибка вычисления reconstruction error")

            # Определение класса и вероятности
            probability = self.sigmoid_transform(reconstruction_error)
            pathology_class = 1 if reconstruction_error > self.optimal_threshold else 0

            # Заполняем результат
            result.update(
                {
                    "probability_of_pathology": float(probability),
                    "pathology_class": pathology_class,
                    "processing_time_seconds": time.time() - start_time,
                    "reconstruction_error": float(reconstruction_error),
                }
            )

            print(
                f"📊 Результат: Ошибка={reconstruction_error:.6f}, "
                f"Вероятность={probability:.3f}, Класс={'Патология' if pathology_class else 'Норма'}"
            )

        except Exception as e:
            error_msg = str(e)
            result.update(
                {
                    "processing_status": "Failure",
                    "error_message": error_msg,
                    "processing_time_seconds": time.time() - start_time,
                }
            )
            print(f"❌ Ошибка обработки: {error_msg}")

        return result


def process_ct_studies(
    study_folders,
    model_path="pathology_autoencoder.keras",
    threshold_path="pathology_threshold.json",
):
    """
    Основная функция для вызова из бэкенда.

    Args:
        study_folders: список путей к папкам с исследованиями
        model_path: путь к файлу модели
        threshold_path: путь к файлу с порогом

    Returns:
        dict: словарь с результатами обработки всех исследований
    """

    print("=" * 60)
    print("🧠 ИИ-сервис для классификации КТ ОГК - ИНФЕРЕНС")
    print("=" * 60)

    # Инициализация процессора
    processor = CTInferenceProcessor()

    # Загрузка модели
    if not processor.load_model(model_path, threshold_path):
        return {
            "overall_status": "Error",
            "error_message": "Не удалось загрузить модель",
            "processed_studies": [],
        }

    # Обработка каждой папки с исследованием
    results = []

    for i, study_folder in enumerate(study_folders):
        if not os.path.exists(study_folder):
            print(f"❌ Папка не существует: {study_folder}")
            continue

        # Обработка исследования
        result = processor.process_study_folder(study_folder, f"study_{i+1:03d}")
        results.append(result)

    # Формируем итоговый отчет
    successful = len([r for r in results if r["processing_status"] == "Success"])
    failed = len([r for r in results if r["processing_status"] == "Failure"])
    pathology_count = len([r for r in results if r.get("pathology_class", 0) == 1])
    normal_count = len([r for r in results if r.get("pathology_class", 0) == 0])

    final_result = {
        "overall_status": "Completed",
        "total_studies_processed": len(results),
        "successful_processing": successful,
        "failed_processing": failed,
        "pathology_cases": pathology_count,
        "normal_cases": normal_count,
        "processing_timestamp": time.strftime("%Y-%m-%d %H:%M:%S"),
        "processed_studies": results,
    }

    print(f"\n📈 Итоговая статистика:")
    print(f"   Всего исследований: {len(results)}")
    print(f"   Успешно обработано: {successful}")
    print(f"   С ошибками: {failed}")
    print(f"   Норма: {normal_count}")
    print(f"   Патология: {pathology_count}")

    return final_result


# Пример использования для тестирования
if __name__ == "__main__":
    # Пример вызова - имитация того, как будет вызываться из бэкенда
    test_folders = [
        "/path/to/study/folder1",
        "/path/to/study/folder2",
        # ... список папок, которые уже распаковал бэкенд
    ]

    # Замените на реальные пути
    results_dict = process_ct_studies(
        study_folders=test_folders,
        model_path="pathology_autoencoder.keras",
        threshold_path="pathology_threshold.json",
    )

    # Бэкенд получит results_dict и сам займется выгрузкой в Excel
    print("\n✅ Инференс завершен! Результаты готовы для выгрузки в Excel.")
