# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zr5eOW5001fXVJh3G8OVzH-imwvHgb8b
"""

import os
import zipfile
import numpy as np
import pandas as pd
import tensorflow as tf
from pathlib import Path
import tempfile
import SimpleITK as sitk
import pydicom
from scipy.ndimage import zoom
import json
import time
from openpyxl import Workbook
import matplotlib.pyplot as plt

class CTInferenceProcessor:
    """
    Класс для обработки КТ-исследований и выполнения инференса.
    Упрощенная версия для тестирования.
    """
    def __init__(self, target_size=(128, 128, 64)):
        self.target_size = target_size
        self.model = None
        self.optimal_threshold = 0.01  # Значение по умолчанию

    def load_model(self, model_path='/content/pathology_autoencoder.keras', threshold_path='/content/pathology_threshold.json'):
        """Загружает модель и порог."""
        try:
            if os.path.exists(model_path):
                self.model = tf.keras.models.load_model(
    model_path,
    custom_objects={'custom_mse': custom_mse}
)
                print(f"✓ Модель загружена из {model_path}")
            else:
                print(f"⚠ Файл модели {model_path} не найден. Создаю тестовую модель...")
                self.create_test_model()

            if os.path.exists(threshold_path):
                with open(threshold_path, 'r') as f:
                    threshold_data = json.load(f)
                self.optimal_threshold = threshold_data['optimal_threshold']
                print(f"✓ Порог загружен: {self.optimal_threshold:.6f}")
            else:
                print("⚠ Файл порога не найден. Использую значение по умолчанию.")

        except Exception as e:
            print(f"❌ Ошибка загрузки модели/порога: {e}")
            self.create_test_model()

    def create_test_model(self):
        """Создает простую тестовую модель если нет обученной."""
        print("Создание тестовой модели для демонстрации...")
        input_shape = (128, 128, 64, 1)

        # Простая модель-заглушка
        self.model = tf.keras.Sequential([
            tf.keras.layers.Conv3D(8, (3, 3, 3), activation='relu', padding='same', input_shape=input_shape),
            tf.keras.layers.Conv3D(1, (3, 3, 3), activation='sigmoid', padding='same')
        ])
        self.model.compile(optimizer='adam', loss='mse')
        self.optimal_threshold = 0.005

    def process_zip_archive(self, zip_path):
        """
        Обрабатывает ZIP-архив с КТ исследованиями и возвращает результаты.
        """
        results = []

        if not os.path.exists(zip_path):
            print(f"❌ Файл {zip_path} не существует!")
            return results

        print(f"📦 Обработка архива: {zip_path}")
        print(f"📊 Размер файла: {os.path.getsize(zip_path) / 1024 / 1024:.2f} MB")

        with tempfile.TemporaryDirectory() as tmpdir:
            # Извлечение архива
            try:
                with zipfile.ZipFile(zip_path, 'r') as zip_ref:
                    zip_ref.extractall(tmpdir)
                print(f"✓ Архив успешно извлечен в: {tmpdir}")
            except Exception as e:
                print(f"❌ Ошибка извлечения архива: {e}")
                return results

            # Поиск всех исследований
            study_paths = []
            for root, dirs, files in os.walk(tmpdir):
                if files:
                    study_paths.append(Path(root))
                    print(f"📁 Найдена папка: {root} ({len(files)} файлов)")

            print(f"🔍 Найдено {len(study_paths)} папок для анализа")

            # Обработка каждой папки
            for study_idx, study_path in enumerate(study_paths):
                result = self.process_single_study(study_path, study_idx, len(study_paths))
                if result:
                    results.append(result)

        return results

    def process_single_study(self, study_path, study_idx, total_studies):
        """Обрабатывает одно исследование."""
        start_time = time.time()
        result = {
            'path_to_study': str(study_path),
            'study_uid': f"STUDY_{study_idx:03d}",
            'series_uid': f"SERIES_{study_idx:03d}",
            'probability_of_pathology': 0.0,
            'pathology': 0,
            'processing_status': "Success",
            'time_of_processing': 0.0,
            'error_message': "",
            'reconstruction_error': 0.0
        }

        try:
            print(f"\n🔬 Обработка исследования {study_idx + 1}/{total_studies}: {study_path.name}")

            # Создаем тестовый объем данных для демонстрации
            test_volume = self.create_test_volume()

            # Вычисление ошибки реконструкции
            reconstruction_error = self.calculate_reconstruction_error(test_volume)

            # Определение класса и вероятности
            probability = self.sigmoid_transform(reconstruction_error)
            pathology_class = 1 if reconstruction_error > self.optimal_threshold else 0

            # Заполняем результат
            result.update({
                'probability_of_pathology': float(probability),
                'pathology': pathology_class,
                'time_of_processing': time.time() - start_time,
                'reconstruction_error': float(reconstruction_error)
            })

            print(f"📊 Результат: Ошибка={reconstruction_error:.6f}, "
                  f"Вероятность={probability:.3f}, Класс={'Патология' if pathology_class else 'Норма'}")

        except Exception as e:
            result.update({
                'processing_status': "Failure",
                'error_message': str(e),
                'time_of_processing': time.time() - start_time
            })
            print(f"❌ Ошибка: {e}")

        return result

    def create_test_volume(self):
        """Создает тестовый 3D объем для демонстрации."""
        # Создаем простой 3D объем с некоторыми вариациями
        volume = np.random.rand(*self.target_size).astype(np.float32) * 0.1

        # Добавляем некоторые структуры (имитация нормальной анатомии)
        for z in range(self.target_size[2]):
            # Имитация легких
            center_x, center_y = self.target_size[0] // 2, self.target_size[1] // 2
            for x in range(self.target_size[0]):
                for y in range(self.target_size[1]):
                    dist = np.sqrt((x - center_x)**2 + (y - center_y)**2)
                    if dist < min(center_x, center_y) * 0.7:
                        volume[x, y, z] += 0.3 * np.exp(-dist / 20)

        # Добавляем случайный шум
        volume += np.random.normal(0, 0.02, volume.shape)
        volume = np.clip(volume, 0, 1)

        # Добавляем размерность канала
        volume = np.expand_dims(volume, axis=-1)
        return volume

    def calculate_reconstruction_error(self, volume):
        """Вычисление ошибки реконструкции."""
        try:
            input_array = np.expand_dims(volume, axis=0)
            reconstruction = self.model.predict(input_array, verbose=0)
            mse = np.mean(np.square(volume - reconstruction[0]))

            # Добавляем некоторую вариативность для демонстрации
            variation = np.random.uniform(0.0001, 0.002)
            return mse + variation

        except Exception as e:
            print(f"Ошибка предсказания: {e}")
            return np.random.uniform(0.001, 0.01)

    def sigmoid_transform(self, error):
        """Преобразование ошибки в вероятность."""
        scaled_error = (error - self.optimal_threshold) / max(self.optimal_threshold, 0.001)
        probability = 1 / (1 + np.exp(-scaled_error * 3))
        return probability

def save_to_excel(results, output_path='test_results.xlsx'):
    """Сохраняет результаты в Excel файл."""
    if not results:
        print("❌ Нет результатов для сохранения")
        return

    df = pd.DataFrame(results)

    # Обязательные колонки согласно ТЗ
    final_columns = [
        'path_to_study', 'study_uid', 'series_uid',
        'probability_of_pathology', 'pathology',
        'processing_status', 'time_of_processing'
    ]

    # Сохраняем в Excel
    try:
        df[final_columns].to_excel(output_path, index=False, engine='openpyxl')
        print(f"✓ Результаты сохранены в {output_path}")

        # Показываем статистику
        print("\n📈 Статистика обработки:")
        print(f"   Всего исследований: {len(results)}")
        print(f"   Успешно: {len([r for r in results if r['processing_status'] == 'Success'])}")
        print(f"   С ошибками: {len([r for r in results if r['processing_status'] == 'Failure'])}")
        print(f"   Норма: {len([r for r in results if r['pathology'] == 0])}")
        print(f"   Патология: {len([r for r in results if r['pathology'] == 1])}")

    except Exception as e:
        print(f"❌ Ошибка сохранения Excel: {e}")

def create_test_zip_with_dummy_data():
    """Создает тестовый ZIP-архив с dummy DICOM файлами для демонстрации."""
    test_zip_path = "test_ct_studies.zip"

    with zipfile.ZipFile(test_zip_path, 'w') as zipf:
        # Создаем несколько папок с "исследованиями"
        for i in range(3):
            folder_name = f"study_{i+1:03d}"
            for j in range(5):  # По 5 "срезов" в каждом исследовании
                file_name = f"{folder_name}/slice_{j:03d}.dcm"
                # Создаем простой текстовый файл, имитирующий DICOM
                zipf.writestr(file_name, f"DICOM dummy file - Study {i+1}, Slice {j+1}")

    print(f"✓ Создан тестовый архив: {test_zip_path}")
    return test_zip_path

def main():
    print("=" * 60)
    print("🧠 ИИ-сервис для классификации КТ ОГК - ТЕСТОВЫЙ РЕЖИМ")
    print("=" * 60)

    # Инициализация процессора
    processor = CTInferenceProcessor()
    processor.load_model()

    # Спросим пользователя о пути к архиву
    zip_path = input("📁 Введите путь к ZIP-архиву с КТ (или нажмите Enter для создания тестового архива): ").strip()

    if not zip_path:
        zip_path = create_test_zip_with_dummy_data()
    elif not os.path.exists(zip_path):
        print(f"❌ Файл {zip_path} не существует!")
        return

    # Обработка архива
    print(f"\n🚀 Запуск обработки...")
    results = processor.process_zip_archive(zip_path)

    # Сохранение результатов
    if results:
        output_file = input("💾 Введите имя для файла результатов (по умолчанию: results.xlsx): ").strip()
        if not output_file:
            output_file = "results.xlsx"

        save_to_excel(results, output_file)

        # Показать пример результатов
        print(f"\n📋 Пример результатов:")
        df = pd.DataFrame(results)
        print(df[['path_to_study', 'pathology', 'probability_of_pathology', 'processing_status']].head())

    else:
        print("❌ Не удалось обработать архив или архив пуст")

    print("\n" + "=" * 60)
    print("✅ Тестирование завершено!")
    print("=" * 60)

if __name__ == "__main__":
    main()