services:
  pg:
    image: postgres
    environment:
      POSTGRES_DB: indicator
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - indicator_net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d indicator" ]
      interval: 5s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    networks:
      - indicator_net

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    networks:
      - indicator_net
volumes:
  pgdata:

networks:
  indicator_net: