# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zr5eOW5001fXVJh3G8OVzH-imwvHgb8b
"""

import os
import zipfile
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras import layers, models, callbacks
from pathlib import Path
import tempfile
import SimpleITK as sitk
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import json
import pydicom
from scipy.ndimage import zoom

# Создаем кастомную функцию MSE для совместимости
def custom_mse(y_true, y_pred):
    return tf.reduce_mean(tf.square(y_true - y_pred))

class CTDataLoader:
    """
    Класс для загрузки и обработки данных из ZIP-архивов.
    """
    def __init__(self, target_size=(128, 128, 64)):
        self.target_size = target_size
        self.preprocessed_data = {}

    def extract_and_load_zip(self, zip_path, label):
        """
        Извлекает ZIP-архив и загружает все исследования внутри него.
        """
        print(f"Загрузка данных из {zip_path} с меткой '{label}'...")
        data_list = []

        with tempfile.TemporaryDirectory() as tmpdir:
            # Извлечение архива
            with zipfile.ZipFile(zip_path, 'r') as zip_ref:
                zip_ref.extractall(tmpdir)

            # Диагностика: что извлеклось
            print(f"Извлечено в: {tmpdir}")
            base_path = Path(tmpdir)

            # Ищем все папки, которые могут содержать DICOM файлы
            study_dirs = []
            for root, dirs, files in os.walk(base_path):
                root_path = Path(root)

                # Проверяем, есть ли в этой папке файлы (возможно DICOM без расширения)
                if files:
                    study_dirs.append(root_path)
                    print(f"Найдена папка с файлами: {root_path} ({len(files)} файлов)")

            print(f"Найдено {len(study_dirs)} потенциальных исследований в {zip_path}")

            for i, study_dir in enumerate(study_dirs):
                try:
                    print(f"Обработка исследования {i + 1}/{len(study_dirs)}: {study_dir}")

                    # Загрузка DICOM серии
                    sitk_image = self.load_dicom_series(study_dir)
                    if sitk_image is None:
                        print(f"Не удалось загрузить DICOM из {study_dir}")
                        continue

                    # Предобработка
                    processed_volume = self.preprocess_image(sitk_image)
                    data_list.append(processed_volume)

                    print(f"Успешно обработано исследование {i + 1}/{len(study_dirs)}")

                except Exception as e:
                    print(f"Ошибка обработки {study_dir}: {e}")
                    continue

        self.preprocessed_data[label] = data_list
        print(f"Успешно загружено {len(data_list)} исследований для метки '{label}'")
        return data_list

    def is_dicom_file(self, file_path):
        """Проверяет, является ли файл DICOM файлом."""
        try:
            pydicom.dcmread(file_path, stop_before_pixels=True)
            return True
        except:
            return False

    def load_dicom_series(self, directory_path):
        """Загружает серию DICOM файлов из папки."""
        try:
            # Получаем все файлы в папке
            all_files = list(Path(directory_path).iterdir())
            files = [f for f in all_files if f.is_file() and not f.name.startswith('.')]

            if not files:
                print(f"Нет файлов в {directory_path}")
                return None

            print(f"Найдено {len(files)} файлов в {directory_path}")

            # Пробуем определить DICOM файлы
            dicom_files = []
            for file_path in files:
                if self.is_dicom_file(str(file_path)):
                    dicom_files.append(str(file_path))

            if not dicom_files:
                print("Не найдено DICOM файлов по сигнатуре, пробуем загрузить все файлы...")
                dicom_files = [str(f) for f in files]

            print(f"Загружаем {len(dicom_files)} файлов как DICOM")

            # Сортируем файлы для правильной последовательности
            dicom_files.sort()

            reader = sitk.ImageSeriesReader()
            reader.SetFileNames(dicom_files)
            image = reader.Execute()
            print(f"Успешно загружено изображение размером {image.GetSize()}")
            return image

        except Exception as e:
            print(f"Ошибка загрузки DICOM из {directory_path}: {e}")
            return None

    def preprocess_image(self, sitk_image):
        """
        Препроцессинг КТ-изображения.
        """
        # Конвертация в numpy array и обрезка значений HU
        image_array = sitk.GetArrayFromImage(sitk_image)
        image_array = image_array.astype(np.float32)

        print(f"Исходный размер: {image_array.shape}")

        # Ограничение диапазона HU для фокуса на релевантных тканях
        image_array = np.clip(image_array, -1000, 400)

        # Нормализация к диапазону [0, 1]
        image_array = (image_array - (-1000)) / (400 - (-1000))

        # Ресемплинг к целевому размеру
        zoom_factors = [
            self.target_size[0] / image_array.shape[0],
            self.target_size[1] / image_array.shape[1],
            self.target_size[2] / image_array.shape[2]
        ]
        image_array_resized = zoom(image_array, zoom_factors, order=1)

        print(f"Размер после ресемплинга: {image_array_resized.shape}")

        # Добавление размерности канала
        image_array_resized = np.expand_dims(image_array_resized, axis=-1)
        return image_array_resized

def create_autoencoder(input_shape=(128, 128, 64, 1)):
    """
    Создает 3D автоэнкодер с оптимизированной архитектурой.
    """
    inputs = layers.Input(shape=input_shape)

    # Энкодер
    x = layers.Conv3D(16, (3, 3, 3), activation='relu', padding='same')(inputs)
    x = layers.MaxPooling3D((2, 2, 2), padding='same')(x)
    x = layers.Conv3D(32, (3, 3, 3), activation='relu', padding='same')(x)
    x = layers.MaxPooling3D((2, 2, 2), padding='same')(x)
    x = layers.Conv3D(64, (3, 3, 3), activation='relu', padding='same')(x)
    encoded = layers.MaxPooling3D((2, 2, 2), padding='same')(x)

    # Декодер
    x = layers.Conv3D(64, (3, 3, 3), activation='relu', padding='same')(encoded)
    x = layers.UpSampling3D((2, 2, 2))(x)
    x = layers.Conv3D(32, (3, 3, 3), activation='relu', padding='same')(x)
    x = layers.UpSampling3D((2, 2, 2))(x)
    x = layers.Conv3D(16, (3, 3, 3), activation='relu', padding='same')(x)
    x = layers.UpSampling3D((2, 2, 2))(x)
    decoded = layers.Conv3D(1, (3, 3, 3), activation='sigmoid', padding='same')(x)

    autoencoder = models.Model(inputs, decoded)
    autoencoder.compile(optimizer='adam', loss=custom_mse)

    return autoencoder

def augment_data(volume):
    """Аугментация 3D данных для создания дополнительных образцов."""
    augmented_volumes = []

    # Базовые преобразования, которые не меняют форму
    transformations = [
        lambda x: x,  # оригинал
        lambda x: np.flip(x, axis=0),
        lambda x: np.flip(x, axis=1),
        lambda x: np.flip(x, axis=2),
        lambda x: np.flip(np.flip(x, axis=0), axis=1),
        lambda x: np.flip(np.flip(x, axis=0), axis=2),
        lambda x: np.flip(np.flip(x, axis=1), axis=2),
        lambda x: np.flip(np.flip(np.flip(x, axis=0), axis=1), axis=2)
    ]

    # Применяем преобразования
    for transform in transformations:
        aug_volume = transform(volume.copy())

        # Добавляем случайный шум к некоторым образцам
        if np.random.rand() > 0.7:
            noise = np.random.normal(0, 0.01, aug_volume.shape)
            aug_volume = aug_volume + noise
            aug_volume = np.clip(aug_volume, 0, 1)

        augmented_volumes.append(aug_volume)

    return augmented_volumes

def calculate_reconstruction_errors(model, data):
    """Вычисление ошибок реконструкции."""
    errors = []
    for volume in data:
        input_array = np.expand_dims(volume, axis=0)
        reconstruction = model.predict(input_array, verbose=0)
        mse = np.mean(np.square(volume - reconstruction[0]))
        errors.append(mse)
    return errors

def main():
    # Конфигурация
    data_config = {
        'norma': '/content/norma_anon.zip',
        'pneumonia': '/content/pneumonia_anon.zip',
        'pneumotorax': '/content/pneumotorax_anon.zip',
        'covid_19':'/content/CT_COVID19.zip'
    }

    # Используем новый формат .keras
    model_save_path = "pathology_autoencoder.keras"
    threshold_save_path = "pathology_threshold.json"
    batch_size = 2
    epochs = 20

    # Загрузка данных
    data_loader = CTDataLoader(target_size=(128, 128, 64))

    # ОСНОВНОЕ ИЗМЕНЕНИЕ: Загрузка данных с патологией для обучения
    pathology_data = []

    # Загружаем данные пневмонии для обучения
    if data_config.get('pneumonia'):
        try:
            pneumonia_data = data_loader.extract_and_load_zip(data_config['pneumonia'], 'pneumonia')
            pathology_data.extend(pneumonia_data)
        except Exception as e:
            print(f"Ошибка загрузки pneumonia данных: {e}")

    # Загружаем данные пневмоторакса для обучения
    if data_config.get('pneumotorax'):
        try:
            pneumotorax_data = data_loader.extract_and_load_zip(data_config['pneumotorax'], 'pneumotorax')
            pathology_data.extend(pneumotorax_data)
        except Exception as e:
            print(f"Ошибка загрузки pneumotorax данных: {e}")

             # Загружаем данные пневмоторакса для обучения
    if data_config.get('covid_19'):
        try:
            covid_19_data = data_loader.extract_and_load_zip(data_config['covid_19'], 'covid_19')
            pathology_data.extend(covid_19_data)
        except Exception as e:
            print(f"Ошибка загрузки covid_19 данных: {e}")

    if not pathology_data:
        print("Ошибка: Не удалось загрузить данные с патологиями")
        return

    # Подготовка данных для обучения
    X_train = np.array(pathology_data)

    # Аугментация данных если недостаточно образцов
    if len(X_train) < 10:
        print(f"Создание аугментированных данных из {len(X_train)} образцов...")
        augmented_data = []
        for volume in X_train:
            augmented_data.extend(augment_data(volume))
        X_train = np.array(augmented_data)

    # Разделение на тренировочную и валидационную выборку
    X_train, X_val = train_test_split(X_train, test_size=0.2, random_state=42)

    print(f"Данные для обучения: {X_train.shape}")
    print(f"Данные для валидации: {X_val.shape}")

    # Создание и обучение модели
    autoencoder = create_autoencoder()
    autoencoder.summary()

    # Callbacks
    early_stopping = callbacks.EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)
    reduce_lr = callbacks.ReduceLROnPlateau(monitor='val_loss', factor=0.2, patience=3, min_lr=1e-6)
    checkpoint = callbacks.ModelCheckpoint('best_pathology_model.keras', monitor='val_loss', save_best_only=True)

    print("Начало обучения автоэнкодера на данных с патологиями...")

    history = autoencoder.fit(
        X_train, X_train,
        batch_size=batch_size,
        epochs=epochs,
        validation_data=(X_val, X_val),
        callbacks=[early_stopping, reduce_lr, checkpoint],
        shuffle=True,
        verbose=1
    )

    # Сохранение модели
    autoencoder.save(model_save_path)
    print(f"Модель сохранена как {model_save_path}")

    # Визуализация обучения
    plt.figure(figsize=(12, 4))
    plt.subplot(1, 2, 1)
    plt.plot(history.history['loss'], label='Training Loss')
    if 'val_loss' in history.history:
        plt.plot(history.history['val_loss'], label='Validation Loss')
    plt.legend()
    plt.title('Model Loss')

    plt.subplot(1, 2, 2)
    if 'lr' in history.history:
        plt.plot(history.history['lr'], label='Learning Rate')
        plt.legend()
        plt.title('Learning Rate Schedule')
    else:
        plt.text(0.5, 0.5, 'Learning Rate data not available',
                horizontalalignment='center', verticalalignment='center')
        plt.title('Learning Rate Schedule')

    plt.savefig('pathology_training_history.png')
    plt.close()

    # Загрузка нормальных данных для определения порога
    print("Загрузка нормальных данных для определения порога...")
    normal_data = []

    if data_config.get('norma'):
        try:
            normal_data = data_loader.extract_and_load_zip(data_config['norma'], 'norma')
        except Exception as e:
            print(f"Ошибка загрузки нормальных данных: {e}")

    # Вычисление ошибок реконструкции
    pathology_errors = calculate_reconstruction_errors(autoencoder, X_val)
    normal_errors = calculate_reconstruction_errors(autoencoder, normal_data) if normal_data else []

    # Определение оптимального порога
    if not normal_errors:
        print("Предупреждение: нет нормальных данных для определения порога")
        # Используем статистику патологических данных для установки порога
        mean_error = np.mean(pathology_errors)
        std_error = np.std(pathology_errors)
        optimal_threshold = mean_error - 2 * std_error  # Нормальные данные должны иметь меньшую ошибку
    else:
        # ROC анализ для определения порога
        from sklearn.metrics import roc_curve

        # Создание меток и ошибок для ROC анализа
        y_true = [1] * len(pathology_errors) + [0] * len(normal_errors)
        y_scores = pathology_errors + normal_errors

        fpr, tpr, thresholds = roc_curve(y_true, y_scores)
        optimal_idx = np.argmax(tpr - fpr)
        optimal_threshold = thresholds[optimal_idx]

    print(f"Оптимальный порог: {optimal_threshold:.6f}")

    # Сохранение порога
    with open(threshold_save_path, 'w') as f:
        json.dump({'optimal_threshold': float(optimal_threshold)}, f)

    # Визуализация распределения ошибок
    plt.figure(figsize=(10, 6))
    if pathology_errors:
        plt.hist(pathology_errors, bins=30, alpha=0.7, label='Патологии', density=True)
    if normal_errors:
        plt.hist(normal_errors, bins=30, alpha=0.7, label='Норма', density=True)
    plt.axvline(optimal_threshold, color='red', linestyle='--', label=f'Порог: {optimal_threshold:.6f}')
    plt.xlabel('Ошибка реконструкции (MSE)')
    plt.ylabel('Плотность')
    plt.title('Распределение ошибок реконструкции (обучение на патологиях)')
    plt.legend()
    plt.savefig('pathology_error_distribution.png')
    plt.close()

    print("Скрипт завершен успешно!")
    print(f"Модель сохранена: {model_save_path}")
    print(f"Порог сохранен: {threshold_save_path}")
    print("Примечание: Модель обучена на патологических данных, поэтому:")
    print("- Нормальные данные будут иметь более высокую ошибку реконструкции")
    print("- Порог используется для обнаружения нормальных случаев")

if __name__ == "__main__":
    main()